spring.application.name=ormlearn
# ==========================
# Logging
# ==========================
logging.level.org.springframework=INFO
logging.level.com.cognizant=DEBUG

# Hibernate SQL Logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ==========================
# Database
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn

spring.datasource.username=root

spring.datasource.password=15205

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true